# Generated by Django 4.2.6 on 2023-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_alter_clipboard_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
