# Generated by Django 4.2.6 on 2023-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0003_alter_clipboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
