# Generated by Django 4.2.6 on 2023-11-05 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0004_alter_clipboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
