# Generated by Django 4.2.6 on 2023-11-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0005_clipboard_uuid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clipboard',
            table=None,
        ),
    ]
