# Generated by Django 4.2.6 on 2023-11-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0007_alter_clipboard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
