# Generated by Django 4.2.6 on 2023-11-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0008_clipboard_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipboard',
            options={'ordering': ['order', '-created_date']},
        ),
    ]
