# Generated by Django 4.2.6 on 2023-11-10 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0009_alter_clipboard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
