# Generated by Django 4.2.6 on 2023-11-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0010_alter_clipboard_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipboard',
            options={'ordering': ['-order', '-created_date']},
        ),
    ]
