# fly.toml app configuration file generated for clipboard-app on 2023-11-11T20:08:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clipboard-app"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
ALLOWED_HOSTS = "clipboard-app.fly.dev"
CORS_ALLOWED_ORIGIN = "https://joyful-faloodeh-f040f9.netlify.app"
CSRF_TRUSTED_ORIGIN = "https://clipboard-app.fly.dev,https://joyful-faloodeh-f040f9.netlify.app"
# SESSION_COOKIE_DOMAIN = ".clipboard-app.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
